name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}        '      
    - name: Cache
      uses: actions/cache@v3.3.2
      with:  
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
    - name: Setup pnpm, install dependencies, and build APIs
      uses: pnpm/action-setup@v2.4.0
      with:
        version: 8
        run_install: |
          args: [--frozen-lockfile]
      
    - name: Check
      run: pnpm check
    
    - name: Lint
      run: pnpm lint

    - name: Test
      run: pnpm test

